server:
  port: 8766
spring:
  application:
    name: kis-gateway

  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
      password: ${REDIS_PASSWORD:}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  config:
    import: ${SPRING_CONFIG_IMPORT:}
  cloud:
    config:
      username: ${SPRING_CLOUD_CONFIG_USERNAME:}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}