server:
  port: 8766
spring:
  application:
    name: kis-gateway


  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  config:
    import: ${SPRING_CONFIG_IMPORT:}
  cloud:
    config:
      username: ${SPRING_CLOUD_CONFIG_USERNAME:}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:}

